"""add sunbiz detail fields

Revision ID: 6baef0ef65a0
Revises: b2c96797a70a
Create Date: 2025-09-20 07:10:43.069542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6baef0ef65a0'
down_revision = 'b2c96797a70a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=64), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscribers_active'), ['active'], unique=False)

    with op.batch_alter_table('nbp_filings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_nbp_filings_city'))
        batch_op.drop_index(batch_op.f('idx_nbp_filings_county'))
        batch_op.drop_index(batch_op.f('idx_nbp_filings_filing_date'))

    op.drop_table('nbp_filings')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fei_ein', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('effective_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('last_event', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('event_date_filed', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('event_effective_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('registered_agent_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('officers_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_column('officers_json')
        batch_op.drop_column('registered_agent_address')
        batch_op.drop_column('event_effective_date')
        batch_op.drop_column('event_date_filed')
        batch_op.drop_column('last_event')
        batch_op.drop_column('effective_date')
        batch_op.drop_column('fei_ein')

    op.create_table('nbp_filings',
    sa.Column('doc_number', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('filing_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('county', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('registered_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('doc_number', name=op.f('nbp_filings_pkey'))
    )
    with op.batch_alter_table('nbp_filings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_nbp_filings_filing_date'), [sa.literal_column('filing_date DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_nbp_filings_county'), [sa.literal_column('lower(county)')], unique=False)
        batch_op.create_index(batch_op.f('idx_nbp_filings_city'), [sa.literal_column('lower(city)')], unique=False)

    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscribers_active'))

    op.drop_table('subscribers')
    # ### end Alembic commands ###
