"""add Stat and indexes

Revision ID: b2c96797a70a
Revises: 6042f95b95bc
Create Date: 2025-09-19 08:29:54.093680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c96797a70a'
down_revision = '6042f95b95bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jurisdiction_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('count_day', sa.Integer(), nullable=False),
    sa.Column('count_mtd', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jurisdiction_id', 'day', name='uq_stats_jur_day')
    )
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.create_index('ix_stats_jur_day', ['jurisdiction_id', 'day'], unique=False)

    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_county'), ['county'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_filing_date'), ['filing_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_state'), ['state'], unique=False)
        batch_op.create_index('ix_entities_state_city_date', ['state', 'city', 'filing_date'], unique=False)
        batch_op.create_index('ix_entities_state_county_date', ['state', 'county', 'filing_date'], unique=False)
        batch_op.create_index('ix_entities_state_date', ['state', 'filing_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index('ix_entities_state_date')
        batch_op.drop_index('ix_entities_state_county_date')
        batch_op.drop_index('ix_entities_state_city_date')
        batch_op.drop_index(batch_op.f('ix_entities_state'))
        batch_op.drop_index(batch_op.f('ix_entities_name'))
        batch_op.drop_index(batch_op.f('ix_entities_filing_date'))
        batch_op.drop_index(batch_op.f('ix_entities_created_at'))
        batch_op.drop_index(batch_op.f('ix_entities_county'))
        batch_op.drop_index(batch_op.f('ix_entities_city'))

    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.drop_index('ix_stats_jur_day')

    op.drop_table('stats')
    # ### end Alembic commands ###
